# Generated by Django 3.2.13 on 2023-09-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('montadora', models.CharField(max_length=50)),
                ('carroceria', models.CharField(choices=[('C', 'Coupé'), ('S', 'Sedã'), ('SUV', 'SUV')], max_length=3)),
                ('tipo_motor', models.CharField(choices=[('C', 'Combustão'), ('H', 'Híbrido'), ('E', 'Elétrico')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='FichaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('tipo_dados', models.CharField(choices=[('M', 'Motorização'), ('D', 'Desempenho')], max_length=1)),
                ('dados', models.FloatField()),
                ('unidade', models.CharField(choices=[('cv', 'Cavalos'), ('Newton X metros', 'Nm'), ('Quilômetros por hora', 'km/h'), ('s', 'Segundos')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Hobbie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('frequencia', models.CharField(choices=[('N', 'Nunca'), ('E', 'Esporadicamente'), ('S', 'Sempre')], max_length=1)),
                ('prioridade', models.IntegerField()),
                ('categoria', models.CharField(choices=[('L', 'Lazer'), ('E', 'Estudo'), ('S', 'Saúde')], max_length=1)),
            ],
        ),
    ]
